/* auth user */
export const CHECK_CREDENTIALS = 'CHECK_CREDENTIALS';
export const CHECK_CREDENTIALS_FAIL = 'CHECK_CREDENTIALS_FAIL';
export const HANDLE_CHANGE_LOGIN = 'HANDLE_CHANGE_LOGIN';
export const HANDLE_CHANGE_REGISTRATION_LOGIN = 'HANDLE_CHANGE_REGISTRATION_LOGIN';
export const HANDLE_CHANGE_PASSWD = 'HANDLE_CHANGE_PASSWD';
export const HANDLE_CHANGE_REGISTRATION_PASSWD = 'HANDLE_CHANGE_REGISTRATION_PASSWD';
export const REDIRECT_TO_REFERRER = 'REDIRECT_TO_REFERRER';
export const REDIRECT_TO_AUTH = 'REDIRECT_TO_AUTH';
export const REDIRECT_TO_AUTH_SUCCESS = 'REDIRECT_TO_AUTH_SUCCESS';
export const SHOW_WARNING = 'SHOW_WARNING';
export const SHOW_AUTH_WARNING = 'SHOW_AUTH_WARNING';
export const REGISTRATION = 'REGISTRATION';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';
export const RESET_REGISTRATION_FIELDS = 'RESET_REGISTRATION_FIELDS';

/* init data */
export const INIT_LOAD_DATA = 'INIT_LOAD_DATA';
export const INIT_LOAD_DATA_FAIL = 'INIT_LOAD_DATA_FAIL';

export const SET_DATA = 'SET_DATA';
export const SET_DATA_WHEN_CHANGE_MONTHS = 'SET_DATA_WHEN_CHANGE_MONTHS';

export const SET_INITIAL_DATA = 'SET_INITIAL_DATA';
export const SET_DATE = 'SET_DATE';


/* controls list-item */
export const ADD_NEW = 'ADD_NEW';
export const ADD_NEW_FAIL = 'ADD_NEW_FAIL';
export const EDIT = 'EDIT';
export const SAVE = 'SAVE';
export const SAVE_FAIL = 'SAVE_FAIL';
export const CANCEL = 'CANCEL';
export const REMOVE = 'REMOVE';
export const REMOVE_FAIL = 'REMOVE_FAIL';
export const REMOVE_RACE = 'REMOVE_RACE';

/* controls employee */
export const SAVE_EMPLOYEE_SUCCESS = 'SAVE_EMPLOYEE_SUCCESS';
export const SAVE_EMPLOYEE_FAIL = 'SAVE_EMPLOYEE_FAIL';
export const REMOVE_EMPLOYEE_FAIL = 'REMOVE_EMPLOYEE_FAIL';

/* controls project */
export const SAVE_PROJECT_SUCCESS = 'SAVE_PROJECT_SUCCESS';

/* confirm */
export const SHOW_REMOVE_CONFIRM = 'SHOW_REMOVE_CONFIRM';
export const HIDE_REMOVE_CONFIRM = 'HIDE_REMOVE_CONFIRM';

/* Controls */
export const GO_TO_PREVIOS_MONTH = 'GO_TO_PREVIOS_MONTH';
export const GO_TO_NEXT_MONTH = 'GO_TO_NEXT_MONTH';

export const CHOOSE_STATUS = 'CHOOSE_STATUS';
export const CHOOSE_STATUS_FAIL = 'CHOOSE_STATUS_FAIL';
export const SET_STATUS = 'SET_STATUS';
export const REMOVE_STATUS = 'REMOVE_STATUS';

export const CLEAR_DAY = 'CLEAR_DAY';

/* current project */
export const SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT';
export const UPDATE_CURRENT_PROJECT = 'UPDATE_CURRENT_PROJECT';
export const RESET_CURRENT_PROJECT = 'RESET_CURRENT_PROJECT';

export const SAVE_HOURS = 'SAVE_HOURS';
export const SAVE_HOURS_FAIL = 'SAVE_HOURS_FAIL';
export const UPDATE_HOURS = 'UPDATE_HOURS';

/* statistic */
export const SHOW_STATISTIC = 'SHOW_STATISTIC';
export const SHOW_STATISTIC_SUCCESS = 'SHOW_STATISTIC_SUCCESS';
export const HIDE_STATISTIC = 'HIDE_STATISTIC';
export const HIDE_STATISTIC_SUCCESS = 'HIDE_STATISTIC_SUCCESS';
